version: '3.8'
services:
  nodered:
    build: .
    container_name: nodered_prod
    ports:
      - "1880:1880"
    volumes:
      - ./config/settings.js:/data/settings.js
      - plc_config:/usr/src/node-red/config # Shared volume for plc_address_map.json
    environment:
      - TZ=Asia/Seoul
      # Add any production-specific environment variables here
    restart: always
    networks:
      - plc_monitoring_network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_prod
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # MQTT over WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
    networks:
      - plc_monitoring_network

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile.prod # We will create this Dockerfile
    container_name: web_app_prod
    ports:
      - "3003:3000" # Web app frontend
      - "3001:3001" # Web app WebSocket server
    volumes:
      - ./config:/config # Mount host's config directory to /config in container
    depends_on:
      - nodered
      - mosquitto
    restart: always
    networks:
      - plc_monitoring_network

networks:
  plc_monitoring_network:
    driver: bridge

volumes:
  plc_config:

# If you decide to use a named volume for persistent data (e.g., context storage), uncomment this:
# volumes:
#   nodered_data: